x-postgres-config:
  &env_postgres
  POSTGRES_PASSWORD: C7SQKr@g6SwtXNi

x-env-redis:
  &env_redis
  REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_ARGS: "--save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"

x-env-kafka:
  &env_kafka
  KAFKA_BROKER_ID: 1
  KAFKA_BROKER_ADDRESS: kafka:9092
  KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://:9092
  ALLOW_PLAINTEXT_LISTENER: 'yes'
  KAFKA_ENABLE_KRAFT: 'yes'
  KAFKA_CFG_PROCESS_ROLES: broker,controller
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093

services:
  #  messages-worker:
  #    image: gradle:jdk18
  #    hostname: messages-worker
  #    working_dir: /usr/src/app
  #    volumes: [ ./apps/messages-worker:/usr/src/app ]
  #    command: gradle run
  #    mem_limit: 4096MB
  #    environment:
  #      <<: [ *env_redis, *env_mongo, *env_postgres, *env_kafka ]

  #  ws-server:
  #    image: gradle:jdk18
  #    hostname: ws-server
  #    working_dir: /usr/src/app
  #    volumes: [ ./apps/ws-server:/usr/src/app ]
  #    command: gradle run
  #    mem_limit: 4096MB
  #    environment:
  #      <<: [ *env_redis, *env_mongo, *env_postgres, *env_kafka ]

  postgres:
    image: bitnami/postgresql:14.6.0
    hostname: postgres
    restart: always
    ports: [ '5432:5432' ]
    environment:
      <<: *env_postgres

  redis:
    image: redis/redis-stack:6.2.6-v6
    hostname: redis
    restart: always
    ports: [ '6379:6379' ]
    environment:
      <<: *env_redis

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1